#cloud-config
autoinstall:
    version: 1
    locale: en_US.UTF-8
    keyboard:
        layout: us
    # network:
    #     network:
    #         version: 2
    #         ethernets:
    #             enp0s25:
    #                dhcp4: yes
    #             enp3s0: {}
    #             enp4s0: {}
    #         bonds:
    #             bond0:
    #                 dhcp4: yes
    #                 interfaces:
    #                     - enp3s0
    #                     - enp4s0
    #                 parameters:
    #                     mode: active-backup
    #                     primary: enp3s0
    # apt:
    #     primary:
    #         - arches: [default]
    #           uri: http://repo.internal/
    #     sources:
    #         my-ppa.list:
    #             source: "deb http://ppa.launchpad.net/curtin-dev/test-archive/ubuntu $RELEASE main"
    #             keyid: B59D 5F15 97A5 04B7 E230  6DCA 0620 BBCF 0368 3F77
    storage:
        layout:
            name: lvm
            sizing-policy: all
    identity:
        hostname: net-test
        username: user
        password: "$6$FNVTeJzkMf37OOiT$5GZwk20wzsGe3Dbry73R7EYGR2BrkZBoI51/bobrljuBMvVJaF9j/KzjNdUWTsmqvOKHZCa9ETuoXfH44..fy/"
    ssh:
        install-server: yes
        authorized-keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWKciTbe7fZA1Epn5J67EjzZg550vTtcrhvKEv0sS3B
        allow-pw: no
    # snaps:
    #     - name: go
    #       channel: 1.20/stable
    #       classic: true
    # debconf-selections: |
    #     bind9      bind9/run-resolvconf    boolean false
    # packages:
    #     - libreoffice
    #     - dns-server^
    # user-data:
    #     disable_root: false
    # late-commands:
    #     - sed -ie 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=30/' /target/etc/default/grub
    # error-commands:
    #     - tar c /var/log/installer | nc 192.168.0.1 1000
